name: 'Android Build Action'
description: 'Build Android projects with customizable flavors, build types, and output paths'
author: 'GitHub'
branding:
  icon: 'smartphone'
  color: 'green'

inputs:
  project-path:
    description: 'Path to the Android project directory (relative to repository root)'
    required: false
    default: '.'
  
  flavors:
    description: 'Comma-separated list of flavors to build (e.g., "prod,debug" or "prodRelease")'
    required: false
    default: ''
  
  build-type:
    description: 'Build type to use (e.g., release, debug, or custom build types)'
    required: false
    default: 'release'
  
  output-path:
    description: 'Custom output path for APK/AAB files (relative to project root)'
    required: false
    default: ''
  
  output-name:
    description: 'Custom name for the output APK/AAB file (without extension)'
    required: false
    default: ''
  
  gradle-tasks:
    description: 'Additional gradle tasks to run (e.g., "clean", "test")'
    required: false
    default: ''
  
  pre-build-script:
    description: 'Shell script to run before building'
    required: false
    default: ''
  
  post-build-script:
    description: 'Shell script to run after building'
    required: false
    default: ''
  
  gradle-options:
    description: 'Additional gradle options (e.g., "--parallel", "--daemon")'
    required: false
    default: ''
  
  output-type:
    description: 'Output type: "apk" or "aab"'
    required: false
    default: 'apk'

outputs:
  output-file:
    description: 'Path to the generated APK/AAB file'
  
  output-files:
    description: 'JSON array of all generated APK/AAB files'
  
  build-log:
    description: 'Build log output'

runs:
  using: 'node20'
  main: 'dist/index.js'
