name: 'Example Usage'

on:
  workflow_dispatch:
    inputs:
      project-path:
        description: 'Path to Android project'
        required: false
        default: '.'
      flavors:
        description: 'Comma-separated flavors'
        required: false
        default: 'prod'
      build-type:
        description: 'Build type'
        required: false
        default: 'release'

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Android project
      uses: actions/checkout@v4
      with:
        repository: 'your-username/your-android-project'
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Build Android App
      uses: ./
      with:
        project-path: ${{ github.event.inputs.project-path }}
        flavors: ${{ github.event.inputs.flavors }}
        build-type: ${{ github.event.inputs.build-type }}
        output-path: './build-outputs'
        output-name: 'MyApp'
        gradle-tasks: 'clean,test'
        pre-build-script: |
          echo "Starting Android build process..."
          echo "Build configuration:"
          echo "  Flavors: ${{ github.event.inputs.flavors }}"
          echo "  Build Type: ${{ github.event.inputs.build-type }}"
          
          # Create version info
          echo "BUILD_NUMBER=${{ github.run_number }}" >> version.properties
          echo "BUILD_TIME=$(date)" >> version.properties
        
        post-build-script: |
          echo "Build completed successfully!"
          echo "Generated files:"
          ls -la build-outputs/
          
          # Create checksum
          cd build-outputs
          for file in *.apk *.aab; do
            if [ -f "$file" ]; then
              sha256sum "$file" > "$file.sha256"
            fi
          done
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-build-${{ github.run_number }}
        path: |
          build-outputs/
          version.properties
    
    - name: Display Build Info
      run: |
        echo "Build completed!"
        echo "Artifacts uploaded: android-build-${{ github.run_number }}"
